name: pull

on:
  pull_request:
    branches-ignore:
      - nightly
  push:
    branches:
      - main
      - release/*
      - landchecks/*
    tags:
      - ciflow/pull/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' && github.run_id }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  build:
    if: github.repository_owner == 'pytorch'
    name: build
    runs-on: linux.4xlarge
    container:
      image: ghcr.io/pytorch/ci-image:pytorch-linux-jammy-cuda13.0-cudnn9-py3.10-clang18
    timeout-minutes: 480
    steps:
      - name: Setup Linux
        id: setup-linux
        uses: pytorch/pytorch/.github/actions/setup-linux@main
        with:
          use-arc: true
          python-version: "3.10"
          compiler: clang18
          cuda-version: "13.0"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials
        id: aws-creds
        continue-on-error: true
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7
        with:
          role-to-assume: arn:aws:iam::308535385114:role/arc
          aws-region: us-east-1
          role-duration-seconds: 18000

      - name: Build
        id: build
        env:
          BUILD_ENVIRONMENT: linux-jammy-cuda13.0-cudnn9-py3.10-clang18
          BRANCH: ${{ steps.setup-linux.outputs.branch }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          SHA1: ${{ github.event.pull_request.head.sha || github.sha }}
          SCCACHE_BUCKET: ossci-compiler-cache-circleci-v2
          SCCACHE_REGION: us-east-1
          SCCACHE_S3_NO_CREDENTIALS: ${{ steps.aws-creds.outcome != 'success' && 'true' || 'false' }}
          PR_LABELS: ${{ toJson(github.event.pull_request.labels.*.name) }}
          TORCH_CUDA_ARCH_LIST: "7.5"
          OUR_GITHUB_JOB_ID: ${{ steps.setup-linux.outputs.job-id }}
          SKIP_SCCACHE_INITIALIZATION: 1
        shell: bash
        run: |
          .ci/pytorch/build.sh

      - name: Archive artifacts into zip
        run: |
          zip -1 -r artifacts.zip dist/ build/custom_test_artifacts build/lib build/bin .additional_ci_files

      - name: Store PyTorch Build Artifacts on S3
        uses: seemethere/upload-artifact-s3@baba72d0712b404f646cebe0730933554ebce96a
        with:
          name: linux-jammy-cuda13.0-cudnn9-py3.10-clang18
          retention-days: 14
          if-no-files-found: error
          path: artifacts.zip
          s3-bucket: gha-artifacts

  test:
    if: github.repository_owner == 'pytorch'
    name: test
    needs: build
    runs-on: linux.g5.4xlarge.nvidia.gpu
    container:
      image: ghcr.io/pytorch/ci-image:pytorch-linux-jammy-cuda13.0-cudnn9-py3.10-clang18
      options: --gpus all
    timeout-minutes: 60
    steps:
      - name: Setup Linux
        uses: pytorch/pytorch/.github/actions/setup-linux@main
        with:
          use-arc: true
          python-version: "3.10"
          compiler: clang18
          cuda-version: "13.0"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials
        id: aws-creds
        continue-on-error: true
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7
        with:
          role-to-assume: arn:aws:iam::308535385114:role/arc
          aws-region: us-east-1
          role-duration-seconds: 18000

      - name: Download build artifacts
        uses: seemethere/download-artifact-s3@1da556a7aa0a088e3153970611f6c432d58e80e6
        with:
          name: linux-jammy-cuda13.0-cudnn9-py3.10-clang18
          path: .
          s3-bucket: gha-artifacts

      - name: Unpack artifacts
        shell: bash
        run: unzip artifacts.zip

      - name: Test torch.cuda.is_available
        shell: bash
        run: |
          python3.10 -m venv --system-site-packages /tmp/test-venv
          source /tmp/test-venv/bin/activate

          pip install -r requirements.txt
          pip install dist/*.whl

          cd test

          python -c "import torch; assert torch.cuda.is_available(), 'CUDA is not available'"
